version: "3"  # optional since v1.27.0
services:
  database:
    container_name: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_students
  
  api:
    container_name: api_nest
    depends_on:
      - "database"
    build: .
    ports:
      - "3333:3333"
    command: bash -c "
        npm run typeorm:migration
        && npm run start
      "